#! /usr/bin/env bash

#################################################
#        AUTOSTART APPS AND CONFIGURATIONS      #
#################################################
pgrep -x sxhkd >/dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
/home/samy/.config/polybar/launch.sh &
nitrogen --restore &
picom --experimental-backend --config ~/.config/picom/picom.sample.conf &
# mpv --no-video ~/.config/Startup_Sounds/ubuntu_startup_sound.mp3 &
usr/bin/emacs --daemon
xscreensaver -nosplash &
volumeicon &
nm-applet &
blueman-applet &
clipmenud &
dunst -print &

#################################################
#                 WM WORKSPACES                 #
#################################################
bspc monitor -d "      " "      " "       " "       " "       " "       " "       " "       " "       "

#################################################
#                WM CONFIGURATION               #
#################################################
bspc config border_width 0
bspc config window_gap 5
bspc config top_padding 35
bspc config right_padding 0
bspc config left_padding 0
bspc config bottom_padding 0
bspc config top_monocle_padding 0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0
bspc config normal_border_color \#282c34
bspc config focused_border_color \#8f8f8f
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true
# bspc config single_monocle       true

#################################################
#                   WM RULES                    #
#################################################
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a Spotify desktop='^8' follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Discord desktop='^7'
bspc rule -a Zathura state=tiled

#################################################
#                  WM LAYOUTS                   #
#################################################
bsp-layout set tall "      " -- --master-size 0.5
bsp-layout set tall "      " -- --master-size 0.5
bsp-layout set tall "       " -- --master-size 0.5
bsp-layout set wide "       " -- --master-size 0.5
bsp-layout set wide "       " -- --master-size 0.5
bsp-layout set monocle "       " -- --master-size 0.5
bsp-layout set monocle "       " -- --master-size 0.5
bsp-layout set monocle "       " -- --master-size 0.5
bsp-layout set monocle "       " -- --master-size 0.5
