-- General Settings for nvim
require("nvim.settings")
require("nvim.keybindings")
require("nvim.plugins")
require("nvim.colorschemes")
require("nvim.lualine")
require("nvim.telescope")
require("nvim.alpha")
require("nvim.devicons")
require("nvim.nvim-tree")
require("nvim.bufferline")
require("nvim.winsep")
require("nvim.silicon")
require("nvim.illuminate")
require("nvim.indentblankline")
require("nvim.whichkey")
require("nvim.numb")

-- Completion engine and Language server
require("nvim.mason")
require("nvim.lsp")
require("nvim.cmp")
require("nvim.saga")

-- Programming
require("nvim.autopairs")
require("nvim.treesitter")
require("nvim.gitsigns")
require("nvim.comments")
require("nvim.toggleterm")
require("nvim.spectre")
require("nvim.autocommands")
